### ISSUE TITLE
Android虚拟机 上传失败 Can't get a federation token

### ISSUE THREAD

**Issue by cys85** [aliyun/aliyun-oss-react-native#10]
环境是： android 虚拟机；

```
"aliyun-oss-react-native": "^1.0.0-alpha.5",
"react-native": "0.55.4",
"react-native-image-picker": "^0.26.10",
```

采用 initWithPlainTextAccessKey 方式 初始化的 AliyunOSS 调用 asyncUpload API上传， 在IOS下一切正常， android 下 出现异常，异常信息 `[Info] 07-17 14:25:19.988  4873  5287 I ReactNativeJS: { [Error: Can't get a federation token
07-17 14:25:19.988  4873  5287 I ReactNativeJS: [ErrorMessage]: Can't get a federation token] framesToPop: 1, code: 'EUNSPECIFIED' }`

我增加了
```
AliyunOSS.addEventListener('uploadProgress', (p) => {
      console.log('here？');
    });
```
好像这个方法都没有进来

参数格式如下

```
[Info] 07-17 15:31:38.498  4231  5445 I ReactNativeJS: 'bucketName', 'mxb-bucket'
07-17 15:31:38.499  4231  5445 I ReactNativeJS: 'objectKey', '9b00b88bb0e565ef153181269835840383image-0459516f-6e3d-4891-84c9-387c4e89a350.jpg'
07-17 15:31:38.499  4231  5445 I ReactNativeJS: 'url', 'file:///storage/emulated/0/Android/data/com.app_merchant_tao_mian_xi/files/Pictures/image-0459516f-6e3d-4891-84c9-387c4e89a350.jpg'
```

**Comment by cys85** [comment]
我在真机上进行了测试， 同样的问题。

**Comment by luozhang002** [comment]
@cys85 其实这个底层接口调用的也是安卓iOSSDK底层的，实际上这个直接传明文的AK SK的接口已经置为废弃，建议使用STS。后期JS 端也会慢慢把这个接口废弃的

**Comment by cys85** [comment]
@luozhang002 是的， 我这边看到了， 我已经改为了 STS， 实测 好用， 已经通过了， 非常感谢。

**Comment by luozhang002** [comment]
@cys85 因为处于alpha阶段，目前官网还没正式挂，后期修复用户反馈的问题后，会慢慢的发正式版本，同时文档也会同步到阿里云官网

**Comment by cys85** [comment]
@luozhang002 
`AliyunOSS.initWithSecurityToken(signature, accessKey, endPoint, configuration);`
这里面的参数 ‘signature’ 是个对象还是字符串呢，里面是不是包含了 securityToken、accessKeyId、accessKeySecret、expiration

**Comment by cys85** [comment]
@luozhang002  我看ios源码中， 只有3个参数 `RCT_EXPORT_METHOD(initWithServerSTS:(NSString *)server endPoint:(NSString *)endPoint configuration:(NSDictionary *)configuration){` 和文档有一些出入

**Comment by luozhang002** [comment]
@cys85 正确的是这种AliyunOSS.initWithSecurityToken(securityToken, accessKeyId, accessKeySecret, endPoint, configuration); 文档我这边需要修改下的。感谢反馈

**Comment by luozhang002** [comment]
@cys85 文档已更新
