### ISSUE TITLE
IOS can't run with link aliyun-oss-react-native

### ISSUE THREAD

**Issue by Timson020** [aliyun/aliyun-oss-react-native#13]
# Xcode version is 9.4.1

# Step
```
react-native init Ex

cd ./Ex

npm i aliyun-oss-react-native

react-native link aliyun-oss-react-native

// add the tdb, and two framework in Link Frameworks and Librarys

// add the AliYunOssSDK.framework in Frameworks 
```
but can's run 

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/10054336/43047919-b639dbe6-8e11-11e8-98a2-0ffe678db848.png">

# Error

```
ld: framework not found AliyunOSSiOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by luozhang002** [comment]
@Timson020  我本地尝试了react-native link aliyun-oss-react-native ，安卓这边编译是OK的，ios的确遇到了你说的这个问题，这个我在跟。
你可以先手动本地添加，是OK的。
![2018-07-23 10 39 41](https://user-images.githubusercontent.com/5653578/43054599-ee6d4022-8e64-11e8-82e3-1708647bde0c.png)

**Comment by Timson020** [comment]
手动添加，我这边是不行的喔。。。。
我看英文文档再试下

**Comment by luozhang002** [comment]
@Timson020  第三步的 copy items if need 选项勾选上

**Comment by Timson020** [comment]
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/10054336/43055182-b80bd5c2-8e67-11e8-9fe4-3c50a6e2de57.png">


是的 我已经勾选了

第一步需要勾选么？

**Comment by Timson020** [comment]
你xcode的版本是 9.4.1么

**Comment by luozhang002** [comment]
@Timson020 是的

**Comment by Timson020** [comment]
如果方便的话 可以截图
整个步骤我看下么

**Comment by luozhang002** [comment]
@Timson020 ，你重新react-native init X ，然后这三步
![1](https://user-images.githubusercontent.com/5653578/43117777-31458e2c-8f41-11e8-95d7-0841a6f2e5e6.png)

**Comment by kala888** [comment]
一样的错误
```
ld: framework not found AliyunOSSiOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

![image](https://user-images.githubusercontent.com/1215976/43884339-71350784-9be8-11e8-97e8-3cd68c00f87e.png)

**Comment by kala888** [comment]
我的调好了，但是我发现一个问题，按照
对比Example，我发现在ios下面有一个AliyunOSSiOS.framework的文件夹，这个哪里来的，我拷贝到我项目的相同位置，然后在项目上添加这个文件夹，神奇的好了
![image](https://user-images.githubusercontent.com/1215976/43887382-452c902c-9bf1-11e8-8304-788077a03dae.png)

之前失败，我很确定按照步骤三种的做法，我选择了“select Copy items if needed”
```
In XCode, in the project navigator, right click Frameworks ➜ Add Files to [your project's name]. Go to node_modules ➜ aliyun-oss-react-native ➜ AliyunSDK. Add AliyunOSSiOS.framework, and select Copy items if needed in the pop-up box.
```
是不是这里没有生效导致的？

**Comment by luozhang002** [comment]
AliyunOSSiOS.framework 这个东西是我们react-native Ios端依赖的原生ios oss sdk

**Comment by CodingPapi** [comment]
Any updated news?

**Comment by CodingPapi** [comment]
@luozhang002

**Comment by vault13tech** [comment]
> 终于调试出来的。我发现一个问题。
> 对比Example，我发现在Example中ios下面有一个AliyunOSSiOS.framework的文件夹，这个哪里来的？把他拷贝到我的项目中，然后在xcode添加这个文件夹，神奇的好了。
> 
> ![image](https://user-images.githubusercontent.com/1215976/43887382-452c902c-9bf1-11e8-8304-788077a03dae.png)
> 
> 之前失败，我很确定按照步骤三种的做法，我选择了“select Copy items if needed”
> 
> ```
> In XCode, in the project navigator, right click Frameworks ➜ Add Files to [your project's name]. Go to node_modules ➜ aliyun-oss-react-native ➜ AliyunSDK. Add AliyunOSSiOS.framework, and select Copy items if needed in the pop-up box.
> ```
> 是不是这里没有生效导致的？XCode Version 9.4.1 (9F2000)
> 
> 同样法来添加AliyunOSSiOS.framework，
> 1，添加demo中的AliyunOSSiOS.framework可以正常使用，
> 2，添加node_modules中的AliyunOSSiOS.framework，报错
> 
> ```
> ld: framework not found AliyunOSSiOS，
> ```
> 怀疑，发布的包有问题

mac-os: 10.14.2
react-native: 0.57.8
aliyun-oss-react-native: 1.0.0-alpha.7
--
也是遇到此問題，依 @kala888 方法，終於編譯成功...

**Comment by oldfeel** [comment]
按 @kala888 方法+添加ipv6那三个包,成功了

**Comment by yubo725** [comment]
> https://github.com/aliyun/aliyun-oss-react-native/blob/master/Example/ios/Example.xcodeproj/project.pbxproj#L1261
> 
> example add path to Header Search Path
> 
> I add below line to my project's "Framework Search Path"
> 
> ```
> "$(SRCROOT)/../node_modules/aliyun-oss-react-native/ios/AliyunSDK"
> ```
> 
> Build is pass

thanks, I followed your step and it works!
