### ISSUE TITLE
如何同时上传多张图片?

### ISSUE THREAD

**Issue by ResponseState200** [aliyun/aliyun-oss-react-native#16]
如题,使用asyncUpload上传图片,貌似没有看到如何同时上传多张图片,求教

**Comment by luozhang002** [comment]
SDK只提供原子性的操作， 上传多张的业务逻辑需要自己写的。SDK暂不提供多张上传。

**Comment by ResponseState200** [comment]
好的,谢谢

**Comment by clycheng2015** [comment]
我将取到的多张图片循环遍历，再调用单张图片上传的接口，总是上传到一半崩溃，是为什么，好像是OOM了，单张图片也没超过20M啊，我fork了源码，怎么修改都无效，在线求教！
