### ISSUE TITLE
SDK的filepath规则

### ISSUE THREAD

**Issue by iUUCoder** [aliyun/aliyun-oss-react-native#41]
请问`asyncUpload`方法的`filepath`应该传什么值？为何使用绝对路径会报错？

![image](https://user-images.githubusercontent.com/14970262/51421016-559e5500-1bd3-11e9-8ee3-1a0a80c81382.png)

**Comment by iUUCoder** [comment]
解决了，使用绝对路径时，应在路径前加上`file://`，例如：
* 绝对路径：'/storage/emulated/0/DCIM/1547865085622.mp4'
* 实际调用：
    ```
    AliyunOSS.asyncUpload(bucketname, objectKey, 'file:///storage/emulated/0/DCIM/1547865085622.mp4')
    ```

文档不够详细，只能try try try，好苦啊。。。

**Comment by Pzz0912** [comment]
你好，想问下我传的就是这种路径file:///storage/emulated/0/DCIM/Camera/20200117_173930.jpg；
为什么还是报错 Error: /storage/emulated/0/20200117_173930.jpg (No such file or directory)
[

**Comment by iUUCoder** [comment]
> 你好，想问下我传的就是这种路径file:///storage/emulated/0/DCIM/Camera/20200117_173930.jpg；
> 为什么还是报错 Error: /storage/emulated/0/20200117_173930.jpg (No such file or directory)
> [

我遇到的问题是加上 `file://` 就好了，你去掉 `file://` 能传吗？
